apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-db
  labels:
    name: user-db
  namespace: sock-shop
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        name: user-db
    spec:
      containers:
      - name: user-db
        image: quay.io/weaveworks/helloworld:master-07a1b6b
        args:
        - -msg=Ahoy
        ports:
        - containerPort: 80
      - name: sidecar
        image: quay.io/weaveworks/sidecar:master-a000001
        args:
        - -addr=:8080
        ports:
        - containerPort: 8080
